# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-13 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationships',
            name='children',
        ),
        migrations.RemoveField(
            model_name='relationships',
            name='guardians',
        ),
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='roll_no',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='event',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='signin_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='signout_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Relationships',
        ),
    ]
