# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-13 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190513_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='roll_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
